
[entities]

	[entities.moth]
		#How many moths required to destroy a torch - Disabled if set to 0
		#Range: > 0
		moths_to_destroy_torch = 5

		[entities.moth.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 10
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 3
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["byg:araucaria_savanna", "byg:frosted_taiga", "minecraft:old_growth_spruce_taiga", "byg:frosted_coniferous_forest", "minecraft:flower_forest", "minecraft:old_growth_pine_taiga", "minecraft:grove", "byg:forgotten_forest", "minecraft:dark_forest", "byg:guiana_shield", "byg:jacaranda_forest", "minecraft:forest", "byg:cypress_swamplands", "byg:red_oak_forest", "byg:orchard", "byg:skyris_vale", "byg:autumnal_forest", "byg:bayou", "byg:borealis_grove", "minecraft:old_growth_birch_forest", "minecraft:sparse_jungle", "byg:coniferous_forest", "byg:autumnal_taiga", "minecraft:windswept_forest", "byg:ebony_woods", "byg:weeping_witch_forest", "minecraft:snowy_taiga", "byg:redwood_thicket", "byg:temperate_rainforest", "byg:cherry_blossom_forest", "minecraft:swamp", "minecraft:birch_forest", "minecraft:taiga", "byg:aspen_forest", "byg:cika_woods", "byg:maple_taiga", "byg:zelkova_forest"]

			[entities.moth.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.hidebehind]

		[entities.hidebehind.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 8
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 1
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["byg:araucaria_savanna", "byg:frosted_taiga", "minecraft:old_growth_spruce_taiga", "byg:frosted_coniferous_forest", "minecraft:flower_forest", "minecraft:old_growth_pine_taiga", "minecraft:grove", "byg:forgotten_forest", "minecraft:dark_forest", "byg:guiana_shield", "byg:jacaranda_forest", "minecraft:forest", "byg:red_oak_forest", "byg:orchard", "byg:skyris_vale", "byg:autumnal_forest", "byg:bayou", "byg:borealis_grove", "minecraft:old_growth_birch_forest", "minecraft:sparse_jungle", "byg:coniferous_forest", "byg:autumnal_taiga", "minecraft:windswept_forest", "byg:ebony_woods", "byg:weeping_witch_forest", "minecraft:snowy_taiga", "byg:redwood_thicket", "byg:temperate_rainforest", "byg:cherry_blossom_forest", "minecraft:birch_forest", "minecraft:taiga", "byg:aspen_forest", "byg:cika_woods", "byg:maple_taiga", "byg:zelkova_forest"]
			#Enables biome based variant selection. This will make this entity choose variants tailored to the biome they spawn in (Only applies to natural spawns)
			biome_based_variants = true

			[entities.hidebehind.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.wisp]
		#Allows the entity to despawn freely when no players are nearby, like vanilla monsters do
		can_despawn = false
		#Chance of wisp being hostile (soul stealer). Chance is a percentage out of 100. 0 is never, 100 is always
		#Range: 0.0 ~ 100.0
		hostile_chance = 12.5

		[entities.wisp.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 13
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 3
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["byg:araucaria_savanna", "byg:frosted_taiga", "minecraft:old_growth_spruce_taiga", "byg:frosted_coniferous_forest", "minecraft:flower_forest", "minecraft:old_growth_pine_taiga", "minecraft:grove", "byg:forgotten_forest", "minecraft:dark_forest", "byg:guiana_shield", "byg:jacaranda_forest", "minecraft:forest", "byg:cypress_swamplands", "byg:red_oak_forest", "byg:orchard", "byg:skyris_vale", "byg:autumnal_forest", "byg:bayou", "byg:borealis_grove", "minecraft:old_growth_birch_forest", "minecraft:sparse_jungle", "byg:coniferous_forest", "byg:autumnal_taiga", "minecraft:windswept_forest", "byg:ebony_woods", "byg:weeping_witch_forest", "minecraft:snowy_taiga", "byg:redwood_thicket", "byg:temperate_rainforest", "minecraft:crimson_forest", "byg:cherry_blossom_forest", "minecraft:swamp", "minecraft:birch_forest", "minecraft:warped_forest", "minecraft:taiga", "byg:aspen_forest", "byg:cika_woods", "byg:maple_taiga", "byg:zelkova_forest"]

			[entities.wisp.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.hirschgeist]
		#Allows the entity to despawn freely when no players are nearby, like vanilla monsters do
		can_despawn = false

		[entities.hirschgeist.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 2
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 1
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["byg:araucaria_savanna", "byg:frosted_taiga", "minecraft:old_growth_spruce_taiga", "byg:frosted_coniferous_forest", "minecraft:flower_forest", "minecraft:old_growth_pine_taiga", "minecraft:grove", "byg:forgotten_forest", "minecraft:dark_forest", "byg:guiana_shield", "byg:jacaranda_forest", "minecraft:forest", "byg:red_oak_forest", "byg:orchard", "byg:skyris_vale", "byg:autumnal_forest", "byg:bayou", "byg:borealis_grove", "minecraft:old_growth_birch_forest", "minecraft:sparse_jungle", "byg:coniferous_forest", "byg:autumnal_taiga", "minecraft:windswept_forest", "byg:ebony_woods", "byg:weeping_witch_forest", "minecraft:snowy_taiga", "byg:redwood_thicket", "byg:temperate_rainforest", "byg:cherry_blossom_forest", "minecraft:birch_forest", "minecraft:taiga", "byg:aspen_forest", "byg:cika_woods", "byg:maple_taiga", "byg:zelkova_forest"]

			[entities.hirschgeist.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.zotzpyre]

		[entities.zotzpyre.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 30
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 1
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["byg:twilight_meadow", "byg:frosted_taiga", "minecraft:old_growth_spruce_taiga", "byg:frosted_coniferous_forest", "minecraft:flower_forest", "minecraft:windswept_hills", "minecraft:grove", "byg:forgotten_forest", "minecraft:jagged_peaks", "minecraft:dark_forest", "byg:guiana_shield", "minecraft:forest", "minecraft:snowy_beach", "minecraft:beach", "byg:cypress_swamplands", "byg:red_oak_forest", "minecraft:meadow", "byg:coconino_meadow", "byg:orchard", "byg:skyris_vale", "byg:crag_gardens", "byg:bayou", "minecraft:snowy_slopes", "minecraft:old_growth_birch_forest", "byg:canadian_shield", "minecraft:frozen_peaks", "byg:autumnal_taiga", "byg:ebony_woods", "byg:weeping_witch_forest", "minecraft:jungle", "byg:temperate_grove", "byg:allium_fields", "minecraft:swamp", "minecraft:wooded_badlands", "minecraft:stony_shore", "minecraft:taiga", "byg:zelkova_forest", "minecraft:savanna_plateau", "minecraft:stony_peaks", "minecraft:lush_caves", "byg:araucaria_savanna", "minecraft:old_growth_pine_taiga", "minecraft:windswept_savanna", "byg:jacaranda_forest", "byg:dacite_ridges", "byg:autumnal_forest", "byg:borealis_grove", "minecraft:bamboo_jungle", "byg:amaranth_fields", "byg:rose_fields", "minecraft:sparse_jungle", "minecraft:windswept_gravelly_hills", "byg:coniferous_forest", "minecraft:snowy_plains", "minecraft:windswept_forest", "minecraft:snowy_taiga", "byg:lush_stacks", "byg:redwood_thicket", "byg:red_rock_valley", "byg:temperate_rainforest", "byg:cherry_blossom_forest", "minecraft:birch_forest", "byg:aspen_forest", "byg:cika_woods", "byg:maple_taiga"]

			[entities.zotzpyre.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

